### PR TITLE
Add modify and cancel actions to shipments endpoint

### PR DESCRIPTION
**Pull request by shioyama**

### CODE REVIEW

**Comment by degicat** [comment]
@k2nr Please review this.

**Comment by k2nr** [comment]
Where can I find the API docs?

**Comment by shioyama** [comment]
@k2nr I've left the specs a bit sparse, e.g. didn't check the response from a cancel request because I don't think it's terribly important, although I could add it. There's some duplication in endpoint specs since they're all exercising the same request logic in the background.

**Comment by k2nr** [comment]
LGTM :+1: I think the specs are enough

**Comment by shioyama** [comment]
Thanks!

**Pull request merged**
